### ISSUE TITLE
Create presentation for showoff 1

### ISSUE THREAD

**Issue by marty30** [marty30/Drones-Simulator#29]

**Comment by Tim108** [comment]
[ISEP1.pptx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c36e0b30604300113cf559/125516c66e82c728ace21e0d46c1a7bf13d3c1e5cdf9ad4cae58f3806b1c65267007f07d75d6e07ebe442c005f5f4eae440b5a40adfa8d39baa47e21d40854b088270a36d43703aeba881eba01b2278b4782b4be8d4bc9fa70.pptx)
